# Generated by Django 4.2 on 2023-05-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_offre_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offre',
            table='Offre',
        ),
    ]
